### ISSUE TITLE
Ik snap het niet

### ISSUE THREAD

**Issue by daandewaard** [DarkSoul2002/LaravelEloquentTest#3]
In de code staat ergens "LouiVos". Wat houdt dat in?

**Comment by DarkSoul2002** [comment]
daandewaard, waar staat "LouiVos"?

**Comment by daandewaard** [comment]
Je hebt het net denk ik stiekem weggecomit

**Comment by daandewaard** [comment]
Plus je ontwijkt mijn vraag

**Comment by DarkSoul2002** [comment]
Ik zou niet weten wat dat zou betekenen. En je kan ook bij de vorige commits kijken of het er staat.

**Comment by daandewaard** [comment]
Ja, dat is te ver zoeken voor mij als drukke zakenman. Ik vraag alleen wat "LouiVos" is, dit heb ik namelijk gezien in de code. Dat weet ik zeker

**Comment by DarkSoul2002** [comment]
<img width="220" alt="Schermafbeelding 2020-10-07 om 13 20 39" src="https://user-images.githubusercontent.com/44866353/95324364-e7fef480-089f-11eb-9ae1-0d18ff0fafd8.png">

**Comment by daandewaard** [comment]
wat een stoere man!
